services:
  nginx:
    container_name: nginx-for-keycloak
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy

  keycloak:
    container_name: keycloak-behind-nginx
    image: my-keycloak:latest
    command: start --optimized
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres-for-keycloak
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=temperament-1-impolite
      - KC_HEALTH_ENABLED=true
#      - KC_METRICS_ENABLED=true
      - KC_HOSTNAME_URL=https://${HOSTNAME_URL:-localhost}
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/realms/master"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    container_name: postgres-for-keycloak
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=temperament-1-impolite
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d keycloak -U postgres"]
      interval: 1s
      timeout: 10s
      retries: 10

volumes:
  postgres_data: